// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlaBot_y_zyLQWzq7h3s1fZLS3-6pRKs',
    appId: '1:903370349901:web:0c3194e371b82d0bc82b04',
    messagingSenderId: '903370349901',
    projectId: 'pets-house-881f0',
    authDomain: 'pets-house-881f0.firebaseapp.com',
    storageBucket: 'pets-house-881f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYQRlgq0cHSpP6y6mAFKqjtkoMzy7uC2c',
    appId: '1:903370349901:android:1f10044be16dbd8cc82b04',
    messagingSenderId: '903370349901',
    projectId: 'pets-house-881f0',
    storageBucket: 'pets-house-881f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR9AbwtxfBI_IpmMN_4DZpm1f1_kdzYx8',
    appId: '1:903370349901:ios:446f9d7de1e47178c82b04',
    messagingSenderId: '903370349901',
    projectId: 'pets-house-881f0',
    storageBucket: 'pets-house-881f0.appspot.com',
    iosClientId: '903370349901-k30hioijqc8r1sd0mji41mk23n97crd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.petHouse',
  );
}
